#Agenda

In this notebook, we are going to study:
1. TensorFlow Installation
2. Why TensorFlow?
3. How it works?
4. Representing Tensors
5. Tensor Shape and Rank
6. Types of Tensors
7. Slicing of Tensors
8. Broadcasting with TensorFlow
9. Types of Data and Changing Type of Data
10. Useful TensorFlow Operators



#Tensorflow Installation
If you are using local machine, you can install TensorFlow by using following commands:
1. Install Python 3.x with or without Anaconda
2. CPU: "conda install tensorflow" OR "pip install tensorflow"
3. GPU: "conda install -c anaconda tensorflow-gpu" OR "pip install tensorflow-gpu"

In Google Colaboratory, there is no need of exclusively installing the TensorFlow.

#Why TensorFlow?

TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.
Reference: https://www.tensorflow.org/

TensorFlow is the largest machine learning library in the world, owned and maintained by Google Inc.

#How Tensorflow Works?

TensorFlow has two main components:
1. Graphs
2. Sessions

TensorFlow works by building a graph of defined computations. Nothing is computed or stored in this graph. It is simply a way of defining the operations that have been written in the code.

A TensorFlow sessions allows parts of the graph to be executed. It allocates memory or resources and handles the execution of the operations and computations we have defined.

In some instances we will need to run a session to be able to execute parts of the graph we have created earlier.

#Importing TensorFlow

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


#Tensors

"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It shouldn't surprise you that tensors are a fundemental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.

#Types of Tensors
Before we go to far, I will mention that there are different types of tensors. These are the most used and we will talk more in depth about each as they are used.

1. Variable
2. Constant
3. Placeholder
4. SparseTensor

With the exception of Variable all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

#Variables

In [ ]:
a = tf.Variable(0,name = 'input')
b = tf.constant(1)

for i in range(3):
  a = a + b
  print(a)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


#Constants

In [ ]:
a = tf.constant(3)
b = tf.constant(5)

c = a + b
print(c)

tf.Tensor(8, shape=(), dtype=int32)


#Placeholders

Inserts a placeholder for a tensor that will be always fed.

In [ ]:
%tensorflow_version 1.x
import tensorflow.compat.v1 as tf

placeholder_ex = tf.placeholder(tf.int32, shape=(1, 2, 3))
print(placeholder_ex)

TensorFlow 1.x selected.
Tensor("Placeholder:0", shape=(1, 2, 3), dtype=int32)


#Sparse Tensors

TensorFlow represents a sparse tensor as three separate dense tensors: indices, values, and shape. In Python, the three tensors are collected into a SparseTensor class for ease of use. If you have separate indices, values, and shape tensors, wrap them in a SparseTensor object before passing to the ops.

TensorFlow Operations, also known as Ops, are nodes that perform computations on or with Tensor objects. After computation, they return zero or more tensors, which can be used by other Ops later in the graph.

#Creating Tensors

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

In [ ]:
string = tf.Variable("My Name is a string", tf.string) 
number = tf.Variable(32, tf.int16)
floating = tf.Variable(31.567, tf.float64)

In [ ]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'My Name is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=31.567>


#Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

In [ ]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
#Determining the rank
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

The rank of a tensor is directly related to the deepest level of nested lists. You can see in the first example ["Test"] is a rank 1 tensor as the deepest level of nesting is 1. Where in the second example [["test", "ok"], ["test", "yes"]] is a rank 2 tensor as the deepest level of nesting is 2.

In [ ]:
rank4_tensor = tf.ones([3, 2, 4, 5])

In [ ]:
print(rank4_tensor)

tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]], shape=(3, 2, 4, 5), dtype=float32)


![alt text](https://www.tensorflow.org/guide/images/tensor/4-axis_block.png)

In [ ]:
print("Type of every element:", rank4_tensor.dtype)
print("Number of dimensions:", rank4_tensor.ndim)
print("Shape of tensor:", rank4_tensor.shape)
print("Elements along axis 0 of tensor:", rank4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


#Indexing
##Single-axis indexing
TensorFlow follow standard python indexing rules, similar to indexing a list or a string in python, and the bacic rules for numpy indexing.

1. indexes start at 0
2. negative indices count backwards from the end
3. colons, :, are used for slices start:stop:step

In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [ ]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


In [ ]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


#Shape of Tensors

The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To get the shape of a tensor we use the shape attribute.

In [ ]:
rank1_tensor.shape

TensorShape([1])

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

In [ ]:
rank4_tensor.shape

TensorShape([3, 2, 4, 5])

#Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

In [ ]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
                                                                             
# The number of elements in the reshaped tensor MUST match the number in the original

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: tensor[dim1, dim2, dim3]

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [ ]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [ ]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three.numpy())  # -> 3

row1 = tensor[0]  # selects the first row
print(row1.numpy())

column1 = tensor[:, 0]  # selects the first column
print(column1.numpy())

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4.numpy())

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3.numpy())


3
[1 2 3 4 5]
[ 1  6 11 16]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[ 6 11]


#Broadcasting with TensorFlow
Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 1, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 2 6], shape=(3,), dtype=int32)


#Type of Data
A tensor can only have one type of data at a time. A tensor can only have one type of data. You can return the type with the property dtype.

In [ ]:
print(x.dtype)

<dtype: 'int32'>


##Changing Type of Data

In [ ]:
type_float = tf.constant(3.142, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)
print(type_float.dtype)
print(type_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


#Useful TensorFlow Operators
We can do basic math on tensors, including addition, element-wise multiplication, matrix multiplication, etc.
Some of the operations are as follows:
* tf.add(a, b)
* tf.subtract(a, b)
* tf.multiply(a, b)
* tf.div(a, b)
* tf.pow(a, b)
* tf.exp(a)
* tf.sqrt(a)

In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.subtract(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
print(a + b, "\n") # element-wise addition
print(a - b, "\n") # element-wise subtraction
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



*End of Tutorial*